# Generated by Django 5.1.3 on 2024-12-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image_link', models.URLField(blank=True, help_text="Link to the book's cover image", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('isbn', models.CharField(help_text='Unique ISBN of the book', max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish_year', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('image_link', models.URLField(blank=True, help_text="Link to the book's cover image", max_length=500, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating out of 10.00', max_digits=3, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
