# Generated by Django 5.1.3 on 2024-12-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(help_text='ID of the user')),
                ('user_rating', models.PositiveIntegerField(help_text='Rating given by the user (0-10)')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', to_field='isbn')),
            ],
        ),
    ]
