# Generated by Django 5.1.3 on 2024-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
